apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service
  namespace: default
  labels:
    app: category-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: category-service
  template:
    metadata:
      labels:
        app: category-service
    spec:
      initContainers:
        - name: wait-for-postgres
          image: bownoed/category-service:a1aa4a59545d142cc6c3efbb665b70ff37cc22c7
          command: ['sh', '-c', 'until nc -z -w 2 postgres-db 5432; do echo waiting for postgres-db; sleep 2; done;']
        - name: wait-for-config-server
          image: bownoed/category-service:a1aa4a59545d142cc6c3efbb665b70ff37cc22c7
          command: ['sh', '-c', 'until nc -z -w 2 config-server 8888; do echo waiting for config-server; sleep 2; done;']
      containers:
        - name: category-service
          image: bownoed/category-service:a1aa4a59545d142cc6c3efbb665b70ff37cc22c7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-db:5432/category_db"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "postgres"
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8082
            initialDelaySeconds: 40
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: category-service
  namespace: default
  labels:
    app: category-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: category-service